### ISSUE TITLE
ANTsR does not build with gcc 4.8.1

### ISSUE THREAD

**Issue by ntustison** [stnava/ANTsR#81]
Hey @stnava ,

Just wanted to mention that the compiler issue we had with the multi start optimizer in ``antsAffineInitializer``/``antsAI`` (https://github.com/stnava/ANTs/issues/278) also prevented me from being able to install ANTsR although ITKR would build and install just fine.  However, switching to gcc 4.2.1 fixed whatever issue was causing this failure.

**Comment by stnava** [comment]
any info on the compilation errors?


brian

**Comment by ntustison** [comment]
Sorry, Brian, but I didn't keep that info.  At the time I just assumed I was doing something wrong.  It wasn't until the brain extraction issue that I thought it might be the compiler.  However, I do remember that ANTs compilation had some weird warnings with gcc 4.8.2.  Most notably, it threw several warnings for an "unused set value" for something like

```
float value = 0.0;
if( argc > 2 )
  {
  value = argv[2];
  }
```
